//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AtomManipulator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ROBOTARM_DIALOG             102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DIALOG2                     130
#define IDC_BUTTON1                     1000
#define IDC_MRVICGO                     1000
#define IDC_MRVIC                       1000
#define IDC_BUTTON2                     1001
#define IDC_SLIDER1                     1002
#define IDC_SLIDER_IKinput_X            1002
#define IDC_SLIDER_Scale                1002
#define IDC_SLIDER2                     1003
#define IDC_SLIDER_IKinput_Y            1003
#define IDC_SLIDER_Rx                   1003
#define IDC_SLIDER3                     1004
#define IDC_SLIDER_IKinput_Z            1004
#define IDC_SLIDER_Ry                   1004
#define IDC_SLIDER_Rz                   1005
#define IDC_EDIT2                       1006
#define IDC_EDIT_MoveY                  1006
#define IDC_EDIT_Y                      1006
#define IDC_CHECK1                      1007
#define IDC_CHECK_CIK                   1007
#define IDC_CHECK_Scenery               1007
#define IDC_CHECK_DrawGround            1007
#define IDC_BUTTON3                     1008
#define IDC_BUTTON4                     1009
#define IDC_BUTTON5                     1010
#define IDC_Potential                   1010
#define IDC_CHECK2                      1011
#define IDC_mOBS                        1011
#define IDC_CHECK_Obstalce              1011
#define IDC_CHECK_DrawSticks            1011
#define IDC_CHECK3                      1012
#define IDC_TAB2                        1014
#define IDC_EDIT_IKinput                1016
#define IDC_Draw_Scene                  1017
#define IDC_BUTTON_LoadModel            1019
#define IDC_BUTTON_LoadScenario         1020
#define IDC_BUTTON_SaveScenario         1021
#define IDC_COMBO_Model2                1027
#define IDC_BUTTON_DelModel             1029
#define IDC_EDIT_MoveX                  1030
#define IDC_EDIT_MoveZ                  1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_SPIN3                       1034
#define IDC_EDIT_ROTA                   1036
#define IDC_EDIT_EEpos1                 1037
#define IDC_EDIT_EEpos2                 1038
#define IDC_EDIT_EEpos3                 1039
#define IDC_SPIN_EEpos1                 1040
#define IDC_SPIN_EEpos2                 1041
#define IDC_SLIDER4                     1042
#define IDC_SPIN_EEpos3                 1043
#define IDC_OCCUPIED_ARM                1044
#define IDC_RECORD_MOTION               1045
#define IDC_BUTTON_SAVESCRIPT           1046
#define IDC_BUTTON_LOADSCRIPT           1047
#define IDC_RECORD_GRASP                1048
#define IDC_BUTTON_Write                1048
#define IDC_RECORD_PUTON                1049
#define IDC_Save_WPath                  1049
#define IDC_Load_WPath                  1050
#define IDC_Clear_WPath2                1051
#define IDC_CHECK4                      1052
#define IDC_CHECK_Motor                 1052
#define IDC_CHECK5                      1053
#define IDC_CHECK_DrawRealArm           1053
#define IDC_BUTTON_InitializeVision     1054
#define IDC_BUTTON6                     1055
#define IDC_BUTTON_CatchBall            1055
#define IDC_KINECT_ON                   1055
#define IDC_BUTTON7                     1056
#define IDC_KINECT_OFF                  1056
#define IDC_BUTTON8                     1057
#define IDC_BUTTON9                     1058
#define IDC_BUTTON10                    1059
#define IDC_BUTTON11                    1063
#define IDC_BUTTON12                    1064
#define IDC_BUTTON13                    1065
#define IDC_BUTTON14                    1066
#define IDC_EDIT_NumPts                 1067
#define IDC_EDIT_X                      1068
#define IDC_EDIT3                       1069
#define IDC_EDIT_Z                      1069
#define IDC_EDIT_NumPts2                1070
#define IDC_EDIT_RX                     1071
#define IDC_EDIT_RY                     1072
#define IDC_EDIT5                       1073
#define IDC_EDIT_RZ                     1073
#define IDC_EDIT4                       1075
#define IDC_KINECT                      1076
#define IDC_LEAP                        1077
#define IDC_FORCE                       1078
#define IDC_TASKS                       1079
#define IDC_AVOID_OURS                  1080
#define IDC_AVOID_DLR                   1081
#define IDC_STATUS                      1082
#define IDC_CHECK12                     1083
#define IDC_CHECK6                      1084
#define IDC_ROBOT_MODE                  1084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
